Enable twitter login
yana-gi/twicode pull request #82
Opened 2021-11-03 09:07 UTC by yana-gi

- [ ] Twitterでログインできるようにする
    - [ ] 'dotenv-rails'導入
    - [ ] omniauth-twitter 導入 
    - [ ] User.rb作成
- [ ] ルーティング設定
    - [ ] 投稿一覧をユーザー別にする
    - [ ] タイトル実装
- [ ] ヘッダーのログインボタン実装

2021-11-07 09:46 UTC, yana-gi commented
@komagata

こちらのPRレビューをお願いできないでしょうか〜🙏
概要や参考にしたリンク等はPRコメントに記載しました。

herokuのreview appでレビュー用にデプロイしてみたので、合わせて確認いただければと思います。
https://twicode-enable-twitter--0dmnc4.herokuapp.com/

## 特に見て欲しいところ
- `spec/system/users_spec.rb`
    - モックテストを初めて作成したため問題ないか見ていただきたいです

2021-11-08 06:29 UTC, komagata commented on spec/system/users_spec.rb
> +        Rails.application.env_config['omniauth.auth'] = twitter_mock
ここって何をやってますかね？
`env_config`ってなんだろう？

2021-11-08 06:31 UTC, komagata commented
今、新規作成ページで「保存する」を押したところこうなっちゃうようです〜

<img width="1458" alt="スクリーンショット 2021-11-08 15 30 40" src="https://user-images.githubusercontent.com/16577/140694554-2ef3209e-17f5-4be9-a704-326c7d623a56.png">

2021-11-10 04:27 UTC, yana-gi commented on spec/system/users_spec.rb
> +        Rails.application.env_config['omniauth.auth'] = twitter_mock
先日の質問タイムでご指摘いただいた通り、ここの処理は不要だったようです。

通常beforeから`twitter_mock`を呼び出すようにし、認証エラーの失敗時のみ`twitter_invalid_mock`を呼び出すように修正しました。先日の質問タイムでご指摘いただいた通り、ここの処理は不要だったようです。

通常beforeから`twitter_mock`を呼び出すようにし、認証エラーの失敗時のみ`twitter_invalid_mock`を呼び出すように修正しました。

2021-11-10 04:29 UTC, yana-gi commented
@komagata 
コメントいただいた点を修正したので確認お願いします〜

review用のアプリですが、すぐ解決できそうにないのですみませんがコードのみ確認いただきたいです🙏

2021-11-10 11:18 UTC, komagata requested changes

2021-11-10 11:18 UTC, komagata commented on spec/system/users_spec.rb
> +    twitter_mock
名詞だと「その名詞の変数を何してるのかな？（引数とをとるわけでもないので無意味に見える）」となるので、どこかで何かを設定しているような動き（現在の動き）であれば動詞を使ってそれを表現するのがいいかもです。（暗黙的な副作用を示すために末尾に`!`をつけるといいかも？）

2021-11-11 10:30 UTC, yana-gi commented on spec/system/users_spec.rb
> +    twitter_mock
確かにそうですね。
`set`という同士をつけて`set_twitter_mock`にしようと思います。

`set`にした理由はREADMEでも`set`という同士が使われていたためです。
https://github.com/omniauth/omniauth/wiki/Integration-Testing#omniauthconfigmock_auth
他にいい動詞があればご指摘頂きたいです〜

> 暗黙的な副作用を示すために末尾に!をつけるといいかも？

この場合の「暗黙的な副作用」とは具体的に何を指すのでしょうか……？

2021-11-14 09:17 UTC, yana-gi commented on spec/system/users_spec.rb
> +    twitter_mock
@komagata 
こちら確認お願いします〜🙋‍♂️ 
（見落とされているかも？と思ったので念の為コメントします）

2021-11-15 09:27 UTC, yana-gi commented on spec/system/users_spec.rb
> +    twitter_mock
📝
`mock_twitter!` / `mock_twitter_failure!` に変更
副作用に関しては下記にメモ
https://scrapbox.io/yana-gi/プログラムにおける「副作用」

2021-11-15 09:29 UTC, merged

2021-11-15 18:33 UTC, komagata reviewed
確認しました、OKですー🙆‍♂️